[package]
name = "rust_password_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = "0.19.3"
aes="0.8.1"
base64="0.13.0"
rustc-serialize = "0.3"
rand = "0.8.5"
rust-crypto = "0.2.36"